# DO NOT EDIT THIS FILE!! 
# IF MODIFIED IN ANY WAY, YOU WILL RECEIVE 0 FOR THE GRADE!

import unittest
from io import StringIO
import sys
from Lab1 import hello_world, input_output

# Test case for hello_world() function
def test_hello_world():
    # Since hello_world() just prints, we can check if the correct output is printed.
    captured_output = StringIO()
    sys.stdout = captured_output

    hello_world()

    # Check if the correct message was printed
    assert captured_output.getvalue().strip() == "Hello, World!"

    # Reset stdout
    sys.stdout = sys.__stdout__

    # Test case for input_output() function
def test_input_output():
    # Sample user inputs for testing
    user_inputs = ["Alice", "25", "5.7"]

    # Redirect stdin to simulate user input
    sys.stdin = StringIO("\n".join(user_inputs))

    # Redirect stdout to capture the printed message
    captured_output = StringIO()
    sys.stdout = captured_output

    # Run the function
    input_output()

    # Get the actual output printed by the input_output() function
    lines = captured_output.getvalue().splitlines()
    actual_output = lines[0].strip().split(":")[3:][0].strip() + "\n" + lines[1].strip() + "\n" + lines[2].strip()

    # Expected output after the function has printed
    expected_output = "Hello, Alice!\nYou are 25 years old.\nYour height is 5.7 meters."

    # Compare the captured output to the expected output
    assert actual_output == expected_output

    # Reset stdin and stdout
    sys.stdin = sys.__stdin__
    sys.stdout = sys.__stdout__

if __name__ == '__main__':
    unittest.main()
